name: pgTAP Tests
on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: supabase/setup-cli@df56b21da46c98abb12a9804e4fb1f657773e333 # v2.0.0
        with:
          version: 2.75.0
      - name: Supabase Start
        run: supabase start
      - name: Run Tests
        run: supabase test db
