name: Check Website Code Formatting with Prettier

on:
  pull_request:
    branches:
      - 'master'

permissions:
  contents: read

jobs:
  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run Prettier
        uses: creyD/prettier_action@8c18391fdc98ed0d884c6345f03975edac71b8f0 # v4.6
        with:
          # Prettier CLI arguments
          prettier_options: '--config ./website/.prettierrc --ignore-path ./website/.prettierignore --check ./website'
