name: Test Linux ARM Build (temporary)

on:
  push:
    branches:
      - rs/fix-linux-arm-release
  workflow_dispatch:

jobs:
  build-linux-arm:
    name: Test Build on Linux arm64
    runs-on: arm-runner
    timeout-minutes: 45
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends curl build-essential libssl-dev pkg-config software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc-15 g++-15
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-15 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-15 100
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-15 100
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-15 100

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: stable

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build and Package
        run: |
          cd cli
          cargo build --release

          # Build gzip package
          cd ./target/release && tar -czvf dbdev.tar.gz ./dbdev
          cd ../..

          # Build debian package
          package_dir="dbdev-${{ github.ref_name }}-linux-arm64"
          mkdir -p "${package_dir}/usr/local/bin"
          cp ./target/release/dbdev "${package_dir}/usr/local/bin/dbdev"

          extension_version="${{ github.ref_name }}"
          # strip the leading v
          deb_version="${extension_version:1}"

          mkdir -p "${package_dir}/DEBIAN"
          touch "${package_dir}/DEBIAN/control"
          echo 'Package: dbdev' >> ${package_dir}/DEBIAN/control
          echo 'Version:' ${deb_version} >> ${package_dir}/DEBIAN/control
          echo 'Architecture: arm64' >> ${package_dir}/DEBIAN/control
          echo 'Maintainer: supabase' >> ${package_dir}/DEBIAN/control
          echo 'Description: CLI for publishing to database.dev' >> ${package_dir}/DEBIAN/control

          # Create deb package
          sudo chmod -R 00755 "${package_dir}"
          sudo dpkg-deb --build "${package_dir}"
